#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: ct-category-v2
spec:
  name: "ct-category-v2"
  version: "1.0"
  description: "API with a simple category cat2 - update"
  contextRef:
    name: "dev-ctx"  
  lifecycle_state: PUBLISHED
  visibility: PUBLIC
  state: STARTED
  local: true
  # primaryOwner:
  #   source: gravitee
  #   sourceId: developers
  #   type: GROUP
  # primaryOwner:
  #   displayName: "Christian Tschacher"
  #   id: "2c9c5927-0e83-4df8-9c59-270e832df8a0"
  categories: 
    - cat1
    - cat2
  plans:
    - name: "KEY_LESS"
      description: "FREE"
      security: "KEY_LESS"
  proxy:
    virtual_hosts:
      - path: "/ct-category-v2"
      # - path: "/unique-path"
    groups:
      - endpoints:
          - name: "Default"
            target: "https://api.gravitee.io/echo"     
