# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: gravitee.io/v1alpha1
kind: Application
metadata:
  name: ct-myapplication-x7
spec:
  contextRef:
    # name: "ct-user"
    name: "dev-ctx"
  name: "ct-myapplication-x7"
  domain: "https://example.com"
  description: "ct K8s Application x7"
  settings:
    app:
      clientId: "dummy-client-id123"
      type: WEB
  metadata:
    - name: "test metadata 1"
      format: "STRING"
    - name: "test metadata 2"
      format: "STRING"
  groups:
    - developers
  members:
  - source: "gravitee"
    sourceId: "christian.tschacher+testuser1@graviteesource.com"
    displayName: "Christian Tschacher"
    role: OWNER
  #    sourceId: "email1@email.example.com"
  #    role: bla
  #  - source: "gravitee"
  #    sourceId: "unknown_user"
  #    role: OWNER
  #  - source: "google"
  #    sourceId: "christian.tschacher@graviteesource.com"
  #    role: USER
  #  - source: "memory"
  #    sourceId: "admin"
  #    role: OWNER
  - source: "memory"
    sourceId: "api1"